# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "2.68.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "2567a33a-6f82-4ecd-97aa-9a651c4340b0"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # increment_build_number

  # build your iOS app
  build_app(
     scheme: "Todo",
    export_method: "appstore"
  )
 # gym
  cert
  sigh(force: true)
  # upload to Beta by Crashlytics
    crashlytics(api_token: "6baee5125152c8e8f9b7dfa6c862a10005578358", build_secret: "4b1b1bd7cdf9bfbca6c0e2b2433f5e18461f9f4933526f45153ebf762ff69cbe", emails: "productscog@gmail.com”)
end
